In [1]:
def ngramas(texto, n):
    """Esta funcion divide el texto en ngramas"""
    texto = texto.replace(" ","").replace("\n","")
    return [texto[i:i+n] for i in range (len (texto) -n+1)]

In [2]:
from collections import Counter
import pandas as pd

In [3]:
def frec_ngramas (texto, n):
    """Calcula las frecuencias de los ngramas de un texto"""
    ng = ngramas(texto,n)
    frecuencias = Counter(ng)
    return pd.DataFrame(frecuencias.most_common(), columns = ['letra', 'frecuencia'])

In [4]:
def leer_frecuencias(archivo):
    """Leer fichero con las frecuencias de los ngramas para el idioma español"""
    return pd.read_csv(archivo, sep = " ", names=['letra', 'frecuencia'])

In [5]:
leer_frecuencias('spanish_monograms.txt')

   letra  frecuencia
0      E    10912000
1      A    10301872
2      O     7398419
3      S     6128524
4      N     5838540
5      I     5694616
6      R     5450913
7      L     4808679
8      D     4237020
9      C     3648080
10     T     3643515
11     U     3292410
12     P     2266539
13     M     2152702
14     B     1042859
15     G      964043
16     V      811441
17     Q      686200
18     H      670756
19     F      652415
20     Y      651259
21     J      374173
22     Z      344877
23     Ñ      178384
24     X      153120
25     K       64167
26     W       26492

In [10]:
def leer_texto_cifrado(texto_cifrado, n):
    """Lee el texto cifrado y calcula las frecuencias de los ngramas"""
    with open (texto_cifrado, encoding='utf-8' ) as f:
        texto_cifrado = f.readlines()[0]
        return frec_ngramas(texto_cifrado, n)

In [11]:
leer_texto_cifrado('Texto_cifrado_2.txt', 1)

   letra  frecuencia
0      q         404
1      t         345
2      g         246
3      s         188
4      f         187
5      l         183
6      k         177
7      o         157
8      r         132
9      x         121
10     z         116
11     e         100
12     d          79
13     h          65
14     w          57
15     ,          47
16     u          33
17     c          28
18     i          24
19     j          24
20     .          22
21     n          16
22     y          14
23     m           8
24     H           7
25     p           6
26     T           5
27     S           3
28     ’           3
29     R           3
30     I           2
31     Z           2
32     L           2
33     “           2
34     ”           2
35     X           1
36     3           1
37     8           1
38     V           1
39     b           1
40     :           1
41     E           1

## ANALISIS DE CIFRADO

In [12]:
monogramas_es = leer_frecuencias ("spanish_monograms.txt")
monogramas_es.head(10)

  letra  frecuencia
0     E    10912000
1     A    10301872
2     O     7398419
3     S     6128524
4     N     5838540
5     I     5694616
6     R     5450913
7     L     4808679
8     D     4237020
9     C     3648080

In [13]:
monogramas_cifrado = leer_texto_cifrado("Texto_cifrado_2.txt", 1)
monogramas_cifrado.head(10)

  letra  frecuencia
0     q         404
1     t         345
2     g         246
3     s         188
4     f         187
5     l         183
6     k         177
7     o         157
8     r         132
9     x         121

## DEFINIR ALFABETO

In [14]:
import string
{letra: None for letra in string.ascii_lowercase}

{'a': None,
 'b': None,
 'c': None,
 'd': None,
 'e': None,
 'f': None,
 'g': None,
 'h': None,
 'i': None,
 'j': None,
 'k': None,
 'l': None,
 'm': None,
 'n': None,
 'o': None,
 'p': None,
 'q': None,
 'r': None,
 's': None,
 't': None,
 'u': None,
 'v': None,
 'w': None,
 'x': None,
 'y': None,
 'z': None}

In [15]:
alfabeto_permutado = {
    'a': 'w',
    'b': 'x',
    'c': 'v',
    'd': 'm',
    'e': 'c',
    'f': 'n',
    'g': 'o',
    'h': 'p',
    'i': 'h',
    'j': 'q',
    'k': 'r',
    'l': 's',
    'm': 'z',
    'n': 'y',
    'o': 'i',
    'p': 'j',
    'q': 'a',
    'r': 'd',
    's': 'l',
    't': 'e',
    'u': 'g',
    'w': 'b',
    'x': 'u',
    'y': 'f',
    'z': 't',
}

## ANALISIS DE BIGRAMAS

In [16]:
bigramas_es = leer_frecuencias("spanish_bigrams.txt")
bigramas_es.head(10)

  letra  frecuencia
0    DE     2088635
1    ES     1882962
2    EN     1850294
3    EL     1638128
4    LA     1464005
5    OS     1460757
6    ON     1307790
7    AS     1268034
8    ER     1239281
9    RA     1197125

In [17]:
bigramas_cifrado = leer_texto_cifrado("Texto_cifrado_2.txt",2)
bigramas_cifrado.head(20)

   letra  frecuencia
0     tf          63
1     qs          61
2     rt          53
3     qf          53
4     tk          52
5     gl          47
6     tl          47
7     ts          47
8     kq          46
9     sq          46
10    kt          44
11    qw          42
12    zq          40
13    qk          39
14    qr          38
15    fz          36
16    wq          35
17    ql          35
18    oq          34
19    rg          33

## ANALISIS DE TRIGRAMAS

In [18]:
trigramas_es = leer_frecuencias("spanish_trigrams.txt")
trigramas_es.head(10)

  letra  frecuencia
0   DEL      601928
1   QUE      594436
2   ENT      538864
3   ION      450424
4   ELA      439787
5   CON      431589
6   SDE      417925
7   ADE      408906
8   CIO      398883
9   NTE      394852

In [19]:
trigramas_cifrado = leer_texto_cifrado("Texto_cifrado_2.txt", 3)
trigramas_cifrado.head(10)

  letra  frecuencia
0   qwq          33
1   jxt          22
2   qsq          21
3   tkq          20
4   tfz          18
5   fzg          15
6   tlz          14
7   qrg          13
8   wqs          13
9   rts          13

## ALGORITMO DE DESCIFRADO

In [22]:
def algoritmo_descifrado(texto_cifrado, alfabeto_permutado):
    """Descifra el texto cifrado a partir de un alfabeto permutado"""
    texto_plano = ""
    
    with open(texto_cifrado, encoding='utf-8') as f:
        texto_cifrado = f.read()

    for letra in texto_cifrado:
        if letra.lower() in alfabeto_permutado and alfabeto_permutado[letra.lower()] is not None:
            reemplazo = alfabeto_permutado[letra.lower()]
            if letra.isupper():
                texto_plano += reemplazo.upper()
            else:
                texto_plano += reemplazo
        else:
            texto_plano += letra

    return texto_plano

In [23]:
algoritmo_descifrado("Texto_cifrado_2.txt", alfabeto_permutado)

'La voz de Prisciliano se escucho severa como de costumbre. Hombre de mediana estatura, fortachon, de pelo negro azabache y mostacho, de esos denominados aguamieleros. Las cananas que le cruzaban el pecho lo hacian verse imponente, ni un solo cartucho faltaba, las carrilleras estaban completas para alimentar el mauser en cuanto tuviera la oportunidad de darle guste al guste, segun decia. Tenia la cualidad de poseer ojos de aguila, en donde ponia el ojo ponia la bala. Parecia un superdotado para el manejo de las armas, estuviese de pie, pecho tierra, de hincapie, a caballo o montado en el ferrocarril, nunca desperdiciaba una bala. Presumia de administrar a conciencia el parque, tan dificil de conseguir, primero por lo caro, enseguida por la dificultad de localizar al proveedor y, ya que lo tenian, el problema era hacerlo llegar hasta los campamentos revolucionarios. En todo eso pensaba cuando se presentaba la remolina. Una bala es lo mas preciado en esos momentos en que nos jugamos la vida, aseguraba. Por tal motivo, siempre guardaba una bala de calibre 38, de esas que usaban sus revolveres Smith and Veston, que traia colgados uno de cada lado de su cintura. El cinto tambien relucia por el metal dorado de las balas que lo coronaban por completo. Traia una sola bala en la bolsa del pantalon de ranchero que se habia agenciado en la ultima hacienda que atacaron y en donde pudieron proveerse de alimentos, caballos, buenos vinos pa’l general y tanguarniz pa’ la tropa, animales pa’ sacrificar y alimentar a todos los revoltosos que andaban en la bola. Dia tras dia cuidaba que la bolsa del pantalon no fuese a estar rota. Eso era lo que mas cuidaba, ni al mauser le daba tanto mantenimiento como a la raida bolsa delantera del pantalon, ese que por la cantidad de polvo y mugre acumulada no se distinguia de que color era. En sus momentos de ocio, metia la mano derecha en el bolsillo y acariciaba solemnemente su preciado tesoro, esa bala le podia significar en cualquier momento la gloria. Parecia que estuviera frotando su amuleto de la buena suerte, con nadie comentaba de esa mania, a nadie le daba explicaciones del porque durante tanto rato guardaba la mano derecha en el bolsillo. Hubo algunos que se atrevieron a hacerles algunas chanzas, haciendo alusion al leve movimiento al interior del pantalon. En respuesta, y sin que los demas vieran el movimiento agil y rapido, ya tenia las dos manos sobre los revolveres dispuestos a ser sacados de sus fundas: “a la revolucion mi vida, para ustedes puras frias”. Los otros tan solo reculaban y sin chistar se retiraban. De esa manera, poco a poco se le fue conociendo, a sus espaldas, claro esta, como “el jugador”, por aquello de tener la mano metida en la bolsa del pantalon y que quizas estuviese tocando sus partes pudorosas. Pero en realidad no le tenian miedo por su destreza con las armas, sino que le tenian respeto por su entrega a la revolucion. Siempre era el primero en salir al campo de batalla. Cuando el general daba la orden de ataque, el ya estaba encima del enemigo, y si hubiesen registrado el conteo de los muertos causados por cada elemento revolucionario sobre el ejercito federal, sin lugar a dudas Prisciliano hubiera sido el lider absoluto De igual manera, cuando el general ordenaba la retirada, su estampa era la ultima en abandonar el enfrentamiento y, claro esta, con algunos muertitos en su haber.\n–Perate tantito, Prisciliano –dijo el general con tranquilidad–, ¿pos cual es tu prisa? Prisciliano no entendia por que motivo tenia que esperar para matar a esos traidores del pueblo mexicano. A esos que, si la situacion fuera a la inversa, no dudarian en soltarle un plomazo para despedirlo de este mundo. Siempre decia que la revolucion se hizo para matar a esos cabrones, y una vez que hubiesen terminado con ellos, entonces si podrian acabar con los jefes del mal gobierno; los que mandaban a las tropas federales a ejecutar campesinos e indigenas, a esos que protegian desde siempre a los ricos y hacendados; claro esta, sin contar a los extranjeros que venian a disfrutar de todas nuestras riquezas, incluso de nuestras mujeres, pues mas de una ya habia parido chilpayates con pelo guero y ojos azules o verdes. –A la orden mi general –declaraba Prisciliano, levantando la mano derecha para saludar militarmente, tocandose levemente la ceja del ojo derecho con el dedo indice, mismo que hacia una pequena curvatura junto con el medio, anular y menique, mientras el pulgar se plegaba a la palma de la mano. Pero no con esa rigidez de los soldados federales, sino con ese carisma de quien sabe que hay un jefe que da las ordenes y el obedecia, no por obedecer, sino porque sabia que todos estaban ahi por gusto, porque era su deseo ser guiados al triunfo sobre esos cabrones explotadores del pueblo mexicano. Dio media vuelta y hasta que quedo de espaldas al general, bajo el brazo y la mano, de inmediato busco como tomar el mauser que habia dejado recargado sobre el mezquite que les estaba proporcionando la refrescante sombra a los lideres de la revolucion. No estaba enojado, simplemente desesperado, queria terminar lo mas pronto posible con los pelones, asi la justicia llegaria mas pronto a cada uno de los pueblos de todo el pais, de ese pais por el cual sabia que luchaba para liberarlo de cualquier tipo de opresion. Si terminaba con el mal gobierno, entonces podrian darle de comer a todos los pobres, y no solo eso, les proporcionarian ropas para resguardar sus verguenzas y sus frios, los jacales serian mas dignos y evitarian que el mar de chilpayates estuviesen viendo y escuchando como los padres seguian ampliando la poblacion, tal y como mandaba Dios.\nTotal, mas de la mitad de los hijos se moriria mas temprano que pronto; podria ser de hambre, de enfermedades, de exceso de trabajo en la hacienda o en la mina para pagar las deudas de los padres e, incluso, de los abuelos. Tambien se les iba a poder ensenar a leer y escribir para, una vez que estudiaran, aprendieran las leyes para defender sus derechos y que nadie pasara sobre de ellos. Podrian dejarle alguna herencia a los mas pequenos y a los que pronto nacerian, man’que fuese una foto – pensaba Prisciliano. En eso estaba, cuando la voz del vigia grito a los cuatro vientos: –¡Alli viene el ferrocarril... Alli viene el ferrocarril!\n'